version: "3.8"

services:
  node:
    image: node:16.15.1
    restart: always
    command: /bin/sh -c "cd /var/www/ && npm run dev"
    volumes:
      - ../:/var/www

  nginx:
    image: nginx:1.20-alpine
    restart: always
    ports:
      - ${HTTP_PORT}:8084
    volumes:
      - ./images/nginx/conf/:/etc/nginx/conf.d/
      - /etc/letsencrypt/:/etc/nginx/certs/
