version: "3.8"

services:
  english:
    image: node:16-alpine
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    command: /bin/sh -c "cd /var/www/ && npm install && npm run dev"
    volumes:
      - ../:/var/www
